# Shell variables
# Generated by 'wal'
wallpaper="/home/frank/.config/hypr/wallpaper/anime/Yuzuriha-01a.jpg"

# Special
background='#171717'
foreground='#c4c4c3'
cursor='#c4c4c3'

# Colors
color0='#171717'
color1='#A2633F'
color2='#5B843D'
color3='#68934D'
color4='#91AA5F'
color5='#B9A64D'
color6='#794B89'
color7='#99948e'
color8='#6e675a'
color9='#be8869'
color10='#81b757'
color11='#88be68'
color12='#aec77e'
color13='#c6b97c'
color14='#a462bb'
color15='#c4c4c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
