# Shell variables
# Generated by 'wal'
wallpaper="/home/frank/.config/hypr/wallpapers/HT-stream-2-zoom-background.jpg"

# Special
background='#171717'
foreground='#3c3c3d'
cursor='#3c3c3d'

# Colors
color0='#171717'
color1='#523792'
color2='#64589A'
color3='#524CB8'
color4='#906B9E'
color5='#A667D3'
color6='#6C9AC0'
color7='#79797a'
color8='#b6b6b7'
color9='#7d69ad'
color10='#8a81b3'
color11='#7d78c9'
color12='#ab90b6'
color13='#bc8dde'
color14='#90b3cf'
color15='#3c3c3d'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
