--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/frank/.config/hypr/wallpapers/HT-stream-2-zoom-background.jpg"

-- Special
background="#171717"
foreground="#3c3c3d"
cursor="#3c3c3d"

-- Colors
color0="#171717"
color1="#523792"
color2="#64589A"
color3="#524CB8"
color4="#906B9E"
color5="#A667D3"
color6="#6C9AC0"
color7="#79797a"
color8="#b6b6b7"
color9="#7d69ad"
color10="#8a81b3"
color11="#7d78c9"
color12="#ab90b6"
color13="#bc8dde"
color14="#90b3cf"
color15="#3c3c3d"
