--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/frank/.config/hypr/wallpapers/2023_all-shimmers-spill_zoom.jpg"

-- Special
background="#171717"
foreground="#3c3c3c"
cursor="#3c3c3c"

-- Colors
color0="#171717"
color1="#A3493F"
color2="#48A34E"
color3="#C09D50"
color4="#232299"
color5="#4446BB"
color6="#B756AD"
color7="#797979"
color8="#b6b6b6"
color9="#ba766f"
color10="#75ba7a"
color11="#cfb57b"
color12="#5a59b2"
color13="#7274cc"
color14="#c980c1"
color15="#3c3c3c"
