# Shell variables
# Generated by 'wal'
wallpaper="/home/frank/.config/hypr/wallpapers/2023_all-shimmers-spill_zoom.jpg"

# Special
background='#171717'
foreground='#3c3c3c'
cursor='#3c3c3c'

# Colors
color0='#171717'
color1='#A3493F'
color2='#48A34E'
color3='#C09D50'
color4='#232299'
color5='#4446BB'
color6='#B756AD'
color7='#797979'
color8='#b6b6b6'
color9='#ba766f'
color10='#75ba7a'
color11='#cfb57b'
color12='#5a59b2'
color13='#7274cc'
color14='#c980c1'
color15='#3c3c3c'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
