--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/frank/.config/hypr/wallpaper/anime/Yuzuriha-01a.jpg"

-- Special
background="#171717"
foreground="#c4c4c3"
cursor="#c4c4c3"

-- Colors
color0="#171717"
color1="#A2633F"
color2="#5B843D"
color3="#68934D"
color4="#91AA5F"
color5="#B9A64D"
color6="#794B89"
color7="#99948e"
color8="#6e675a"
color9="#be8869"
color10="#81b757"
color11="#88be68"
color12="#aec77e"
color13="#c6b97c"
color14="#a462bb"
color15="#c4c4c3"
